---
title: "Prior specification"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Prior specification}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Overview

Encoding prior information into a model via prior probability distributions is rarely a simple mapping. We need to ensure the prior distributions give credible probabilities of observing each parameters values, and that together, the joint prior distribution predicts credible outcomes of interest.

In practice, prior specification requires a bit of tinkering to correctly encode information in to both the priors for parameters that have interpretable values, and the predictions of joint priors for the parameters that have less interpretable values.

To be clear, we don't want the priors to overfit the specific realisation of data available, instead the prior should generalise to all plausible data that could be generated by the species-environment relationship we wish to model.

Two articles are created to help encode information into the priors for these `modskurt` models:

The `modskurt` **mean function** that describes the shape of average abundance along the gradient in question: 

- [Modskurt priors](./modskurt-priors.html)

The negative binomial-based **abundance distributions** that describe the probability of observing different species counts and excess-zeros given the `modskurt` mean: 

- https://salt-ecology.shinyapps.io/nb-zinbl-prior-specs/

## In practice

Todo...
